CREATE TABLE MEMBER_TB (
	MEMBER_ID VARCHAR2(20) CONSTRAINT MEMBER_ID_PK PRIMARY KEY,
	MEMBER_NAME	VARCHAR2(15) NOT NULL,
	PROFILE_IMG	VARCHAR2(300) DEFAULT 'DEFAULT_PROFILE.jpg' NOT NULL,
	PASSWORD VARCHAR2(400) DEFAULT '1234' NOT NULL,
	MEMBER_NO VARCHAR2(300) NULL,
	PHONE VARCHAR2(50) NULL,
	ADDRESS	VARCHAR2(100) NULL,
	EMAIL VARCHAR2(100) NULL,
	HIRE_DATE DATE DEFAULT SYSDATE NOT NULL,
	ENT_DATE DATE NULL,
	SALARY NUMBER NULL,
	LEAVE NUMBER DEFAULT 0 NULL,
	DEPT_CODE VARCHAR2(20) NOT NULL CONSTRAINT MEMBER_DEPT_FK REFERENCES DEPARTMENT_TB(DEPT_CODE),
	JOB_CODE VARCHAR2(20) NOT NULL CONSTRAINT MEMBER_JOB_FK REFERENCES JOB_TB(JOB_CODE)
);

COMMENT ON COLUMN MEMBER_TB.MEMBER_ID IS '생성 년월일+시퀀스번호';
INSERT INTO MEMBER_TB VALUES(TO_CHAR(SYSDATE,'YYMMDD')||SEQ_MEMBER_ID.NEXTVAL,'김맹구',DEFAULT,DEFAULT,'980707-2000000','01011112222','서울시 금천구 가산동',
	NULL,DEFAULT,NULL,2000000,DEFAULT,'D1','J4');
COMMIT;
SELECT * FROM MEMBER_TB JOIN DEPARTMENT_TB USING(DEPT_CODE) JOIN JOB_TB USING(JOB_CODE);
CREATE TABLE DEPARTMENT_TB (
	DEPT_CODE VARCHAR2(20) CONSTRAINT DEPT_CODE_PK PRIMARY KEY,
	DEPT_NAME VARCHAR2(100)	NOT NULL
);
DROP TABLE DEPARTMENT_TB;
CREATE TABLE JOB_TB(
	JOB_CODE VARCHAR2(20) CONSTRAINT JOB_CODE_PK PRIMARY KEY,
	JOB_NAME VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_DEPT_CODE
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_JOB_CODE
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_MEMBER_ID
START WITH 1
INCREMENT BY 1
NOMINVALUE
MAXVALUE 99
CYCLE
NOCACHE;
DROP SEQUENCE SEQ_MEMBER_ID;
SELECT * FROM DEPARTMENT_TB;
INSERT INTO DEPARTMENT_TB VALUES('D'||SEQ_DEPT_CODE.NEXTVAL,'운영팀');
INSERT INTO DEPARTMENT_TB VALUES('D'||SEQ_DEPT_CODE.NEXTVAL,'행정팀');
INSERT INTO DEPARTMENT_TB VALUES('D'||SEQ_DEPT_CODE.NEXTVAL,'인사팀');
INSERT INTO DEPARTMENT_TB VALUES('D'||SEQ_DEPT_CODE.NEXTVAL,'경영팀');
INSERT INTO DEPARTMENT_TB VALUES('D'||SEQ_DEPT_CODE.NEXTVAL,'홍보팀');
COMMIT;
SELECT * FROM JOB_TB;
INSERT INTO JOB_TB VALUES('J'||SEQ_JOB_CODE.NEXTVAL,'대표');
INSERT INTO JOB_TB VALUES('J'||SEQ_JOB_CODE.NEXTVAL,'부사장');
INSERT INTO JOB_TB VALUES('J'||SEQ_JOB_CODE.NEXTVAL,'팀장');
INSERT INTO JOB_TB VALUES('J'||SEQ_JOB_CODE.NEXTVAL,'사원');

