<<<<<<< HEAD
SELECT * FROM MEMBER_TB;

CREATE TABLE DRAFT_APPROVE_TB(
	APPROVE_NO NUMBER PRIMARY KEY,
	APPROVE_TITLE VARCHAR2(100),
	APPROVE_CONTENT VARCHAR2(2000),
	CURRENT_DATE DATE DEFAULT SYSDATE ,
	MEMBER_ID VARCHAR2(20) REFERENCES MEMBER_TB(MEMBER_ID) ON DELETE CASCADE,/* MEMBER_TB 삭제시 DRAFT_APPROVE_TB테이블도 삭제 */
	APPROVE_STATE VARCHAR2(20) DEFAULT '미작성',  /* 기본값 적용 */
	APPROVE_KIND VARCHAR2(30) CHECK(APPROVE_KIND IN('연장근무신청서','근태신청서','사직서','반차','연차','보건','경조','외출','조퇴')) /* CHECK 조건 */
);

SELECT * FROM DRAFT_APPROVE_tB;
SELECT * FROM DRAFT_APPROVE_TB WHERE MEMBER_ID='20177043';

CREATE SEQUENCE SEQ_APPROVE_NO /* 전자결재번호 시퀀스번호 */
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;  /* 시퀀스 생성 */

 
CREATE TABLE APPROVE_LINE_TB(  /* 결재선 테이블 생성 */
	APPROVE_LINE_NO NUMBER PRIMARY KEY,
	APPROVE_ORDER NUMBER NOT NULL,
	APPROVE_NO NUMBER REFERENCES DRAFT_APPROVE_TB(APPROVE_NO) ON DELETE CASCADE,
	APPROVE_STATUS VARCHAR2(10) DEFAULT '대기',
	APPROVE_DATE DATE,
	MEMBER_ID VARCHAR2(20) REFERENCES MEMBER_TB(MEMBER_ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_APPROVELINE_NO /* 결재선 시퀀스 번호 생성 */
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;

SELECT * FROM DRAFT_APPROVE_TB WHERE MEMBER_ID='20177043';
SELECT * FROM APPROVE_LINE_TB;
INSERT INTO APPROVE_LINE_TB VALUES(SEQ_APPROVELINE_NO.NEXTVAL,1,4,DEFAULT,NULL,20177043);


CREATE TABLE TIME_TB( /* 시간테이블 생성 */
	TIME_NO NUMBER PRIMARY KEY,
	START_TIME DATE,
	END_TIME DATE,
	APPROVE_NO NUMBER REFERENCES DRAFT_APPROVE_TB(APPROVE_NO) ON DELETE CASCADE
)

CREATE SEQUENCE SEQ_TIME_NO /* 시간번호 시퀀스 생성 */
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;


CREATE TABLE REFERENCE_LINE( /* 참조선 테이블 생성 */
	REFERENCE_LINE_NO NUMBER PRIMARY KEY,
	APPROVE_NO NUMBER REFERENCES DRAFT_APPROVE_TB(APPROVE_NO) ON DELETE CASCADE,
	MEMBER_ID VARCHAR2(20) REFERENCES MEMBER_TB(MEMBER_ID) ON DELETE CASCADE
)

CREATE SEQUENCE SEQ_REFERENCELINE_NO /* 참조선 시퀀스 번호 생성 */
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;


CREATE TABLE APPROVE_ATTACH_TB( /* 결재첨부파일 테이블 생성 */
	AFILE_NO NUMBER PRIMARY KEY,
	AFILE_NAME VARCHAR2(50) NOT NULL,
	APPROVE_NO NUMBER REFERENCES DRAFT_APPROVE_TB(APPROVE_NO) ON DELETE CASCADE
)

CREATE SEQUENCE SEQ_AFILE_NO  /* 파일번호 시퀀스 생성 */
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;


CREATE TABLE EXPENDITURE_APP( /* 지출결의서 테이블 생성 */
	EXPENDITURE_APP_NO NUMBER PRIMARY KEY,
	APPROVE_NO NUMBER REFERENCES DRAFT_APPROVE_TB(APPROVE_NO) ON DELETE CASCADE,
	ACCOUNT VARCHAR2(500),
	USE_HISTORY VARCHAR2(500),
	PRICE VARCHAR2(20)
);

CREATE SEQUENCE SEQ_EXPENDITURE_NO/* 지출결의서 시퀀스번호 생성 */
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;


=======
<<<<<<< HEAD
SELECT D.DEPT_CODE, DEPT_NAME, COUNT(MEMBER_ID) AS DEPT_COUNT
FROM DEPARTMENT_TB D LEFT JOIN MEMBER_TB M ON D.DEPT_CODE=M.DEPT_CODE
GROUP BY D.DEPT_CODE, DEPT_NAME
ORDER BY D.DEPT_CODE ASC;

SELECT JOB_CODE, JOB_NAME, COUNT(*) AS JOB_COUNT
		FROM MEMBER_TB JOIN JOB_TB USING(JOB_CODE)
		GROUP BY JOB_CODE, JOB_NAME
		ORDER BY JOB_CODE ASC;
SELECT * FROM JOB_TB;
ALTER TABLE JOB_TB ADD JOB_AUTH VARCHAR2(50);
UPDATE JOB_TB SET JOB_AUTH='EMP' WHERE JOB_CODE='J4';
COMMIT;
SELECT * FROM MEMBER_TB JOIN DEPARTMENT_TB USING(DEPT_CODE);
SELECT * FROM DEPARTMENT_TB;
INSERT INTO DEPARTMENT_TB VALUES('D6','홍보1팀');
UPDATE MEMBER_TB SET DEPT_CODE='D1' WHERE JOB_CODE='J1';
SELECT * FROM MEMBER_TB;
ALTER TABLE MEMBER_TB DROP CONSTRAINT MEMBER_JOB_FK;
ALTER TABLE MEMBER_TB DROP CONSTRAINT SYS_C0071624;
ALTER TABLE MEMBER_TB MODIFY JOB_CODE CONSTRAINT MEMBER_JOB_FK REFERENCES JOB_TB(JOB_CODE) ON DELETE SET NULL;
ROLLBACK;
UPDATE DEPARTMENT_TB SET DEPT_NAME='영업팀' WHERE DEPT_CODE='D6';

UPDATE MEMBER_TB SET PROFILE_IMG='DEFAULT_PROFILE.png';

ALTER TABLE MEMBER_TB ADD(SUB_ADDRESS VARCHAR2(100));
UPDATE MEMBER_TB SET SUB_ADDRESS='KM타워 304호';
UPDATE MEMBER_TB SET ADDRESS='서울 금천구 가산로 70' WHERE MEMBER_ID IN('23072817','23072118','23072819');
=======
SELECT * FROM MEMBER_TB;

CREATE TABLE DRAFT_APPROVE_TB(
	APPROVE_NO NUMBER PRIMARY KEY,
	APPROVE_TITLE VARCHAR2(100),
	APPROVE_CONTENT VARCHAR2(2000),
	CURRENT_DATE DATE DEFAULT SYSDATE ,
	MEMBER_ID VARCHAR2(20) REFERENCES MEMBER_TB(MEMBER_ID) ON DELETE CASCADE,/* MEMBER_TB 삭제시 DRAFT_APPROVE_TB테이블도 삭제 */
	APPROVE_STATE VARCHAR2(20) DEFAULT '미작성',  /* 기본값 적용 */
	APPROVE_KIND VARCHAR2(30) CHECK(APPROVE_KIND IN('연장근무신청서','근태신청서','사직서','반차','연차','보건','경조','외출','조퇴')) /* CHECK 조건 */
);

SELECT * FROM DRAFT_APPROVE_tB;

CREATE SEQUENCE SEQ_APPROVE_NO /* 전자결재번호 시퀀스번호 */
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;  /* 시퀀스 생성 */

 
CREATE TABLE APPROVE_LINE_TB(  /* 결재선 테이블 생성 */
	APPROVE_LINE_NO NUMBER PRIMARY KEY,
	APPROVE_ORDER NUMBER NOT NULL,
	APPROVE_NO NUMBER REFERENCES DRAFT_APPROVE_TB(APPROVE_NO) ON DELETE CASCADE,
	APPROVE_STATUS VARCHAR2(10) DEFAULT '대기',
	APPROVE_DATE DATE,
	MEMBER_ID VARCHAR2(20) REFERENCES MEMBER_TB(MEMBER_ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_APPROVELINE_NO /* 결재선 시퀀스 번호 생성 */
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;

SELECT * FROM DRAFT_APPROVE_TB WHERE MEMBER_ID='20177043';
SELECT * FROM APPROVE_LINE_TB;
INSERT INTO APPROVE_LINE_TB VALUES(SEQ_APPROVELINE_NO.NEXTVAL,1,4,DEFAULT,NULL,20177043);


CREATE TABLE TIME_TB( /* 시간테이블 생성 */
	TIME_NO NUMBER PRIMARY KEY,
	START_TIME DATE,
	END_TIME DATE,
	APPROVE_NO NUMBER REFERENCES DRAFT_APPROVE_TB(APPROVE_NO) ON DELETE CASCADE
)

CREATE SEQUENCE SEQ_TIME_NO /* 시간번호 시퀀스 생성 */
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;


CREATE TABLE REFERENCE_LINE( /* 참조선 테이블 생성 */
	REFERENCE_LINE_NO NUMBER PRIMARY KEY,
	APPROVE_NO NUMBER REFERENCES DRAFT_APPROVE_TB(APPROVE_NO) ON DELETE CASCADE,
	MEMBER_ID VARCHAR2(20) REFERENCES MEMBER_TB(MEMBER_ID) ON DELETE CASCADE
)

CREATE SEQUENCE SEQ_REFERENCELINE_NO /* 참조선 시퀀스 번호 생성 */
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;


CREATE TABLE APPROVE_ATTACH_TB( /* 결재첨부파일 테이블 생성 */
	AFILE_NO NUMBER PRIMARY KEY,
	AFILE_NAME VARCHAR2(50) NOT NULL,
	APPROVE_NO NUMBER REFERENCES DRAFT_APPROVE_TB(APPROVE_NO) ON DELETE CASCADE
)

CREATE SEQUENCE SEQ_AFILE_NO  /* 파일번호 시퀀스 생성 */
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;


CREATE TABLE EXPENDITURE_APP( /* 지출결의서 테이블 생성 */
	EXPENDITURE_APP_NO NUMBER PRIMARY KEY,
	APPROVE_NO NUMBER REFERENCES DRAFT_APPROVE_TB(APPROVE_NO) ON DELETE CASCADE,
	ACCOUNT VARCHAR2(500),
	USE_HISTORY VARCHAR2(500),
	PRICE VARCHAR2(20)
);

CREATE SEQUENCE SEQ_EXPENDITURE_NO/* 지출결의서 시퀀스번호 생성 */
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;


>>>>>>> 8bb1ac5c4fdc7a1dffebf70b896c0875afb1ec43
>>>>>>> branch 'dev' of https://github.com/songzzak/GDJ64_Finally_final.git
