
SELECT * FROM DRAFT_APPROVE_TB;

DELETE FROM DRAFT_APPROVE_TB WHERE APPROVE_NO = 65;
ALTER TABLE DRAFT_APPROVE_TB MODIFY (APPROVE_KIND VARCHAR2(40));

SELECT SEQ_APPROVE_NO.CURRVAL FROM DUAL;

SELECT *
  FROM all_sequences;
  SEQ_APPROVE_NO;
  
 SELECT * FROM TIME_TB;
 DELETE FROM TIME_TB WHERE TIME_NO = ;

ALTER SEQUENCE SEQ_AFILE_NO MODIFY SEQ_ATTACHMENT_NO;

RENAME SEQ_REFERENCELINE_NO TO SEQ_REFERLINE_NO;

ALTER TABLE APPROVE_ATTACH_TB ADD SAVE_NAME VARCHAR(50);
SELECT * FROM APPROVE_ATTACH_TB;


SELECT * FROM APPROVE_LINE_TB;
SELECT * FROM REFER_LINE_TB;

ALTER TABLE REFER_LINT_TB RENAME TO REFER_LINE_TB;
