SELECT DEPT_CODE, DEPT_NAME, COUNT(*) AS DEPT_COUNT
FROM MEMBER_TB JOIN DEPARTMENT_TB USING(DEPT_CODE)
GROUP BY DEPT_CODE, DEPT_NAME
ORDER BY DEPT_CODE ASC;

SELECT JOB_CODE, JOB_NAME, COUNT(*) AS JOB_COUNT
		FROM MEMBER_TB JOIN JOB_TB USING(JOB_CODE)
		GROUP BY JOB_CODE, JOB_NAME
		ORDER BY JOB_CODE ASC;