SELECT * FROM DRAFT_APPROVE_TB WHERE MEMBER_ID ='20177043';

INSERT INTO DRAFT_APPROVE_TB values(5,'두번째기안서','작성하자',DEFAULT,20177043,DEFAULT,'연장근무신청서');

SELECT * FROM APPROVE_ATTACH_TB;

SELECT * FROM APPROVE_LINE_TB;

SELECT * FROM EXPENDITURE_APP;

SELECT * FROM FILE_ATTATCH_TB;

